parent(pam,bob).
parent(tom,bob).
parent(tom,liz).
parent(bob,ann).
parent(bob,pat).
parent(pat,jim).
male(tom).
male(bob).
male(pat).
male(jim).
female(pam).
female(liz).
female(ann).
mother(X,Y):-parent(X,Y),female(X).
father(X,Y):-parent(X,Y),male(X).
grandparent(X,Y):-parent(X,Z),parent(Z,Y).
sister(X,Y):-parent(Z,X),parent(Z,Y),female(X).
brother(X,Y):-parent(Z,X),parent(Z,Y),male(X).
grandfather(X,Y):-parent(X,Z),parent(Z,Y),male(X).
grandchild(X,Y):-parent(Y,Z),parent(Z,X).
grandson(X,Y):-grandchild(X,Y),male(X).
uncle(X,Y):-parent(Z,X),brother(Y,Z).
